// AUTO-GENERATED by scripts/sync-home-videos.mjs — do not edit manually
// locale: en | generated: 2026-08-22T07:46:20.930Z

import type { HomeVideo } from '../lib/youtube';

export const homeVideosLocale = 'en' as const;

/** Top 10 videos for homepage strip (duplicated for seamless scroll). */
export const homeVideos: HomeVideo[] = [
  {
    "url": "https://www.youtube.com/watch?v=Z7yiAT52_Ew",
    "title": "Openterface uConsole KVM Ext Module V2",
    "author": "RGhandhelds",
    "channelAvatar": "https://yt3.ggpht.com/_fe-uRZnAvnaYwrIWZbCP7t3cLC39MNVMqD2-OzXpwnejdTVTz5F2zYT4EekyvKeeD-2bjLhbg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/Z7yiAT52_Ew/hqdefault.jpg",
    "date": "2026-08-15",
    "views": 248,
    "viewsFormatted": "248"
  },
  {
    "url": "https://www.youtube.com/watch?v=MydkuIGCO3o",
    "title": "Openterface KeyMod: Full Keyboard and Mouse in Your Pocket",
    "author": "Sam's eXperiments logs",
    "channelAvatar": "https://yt3.ggpht.com/QypC0fMJdJDxdf_04lp6TWkuorFPB9pVZD8oOLwclsvRfJsfzCz01iaSl56A1J9lcCHUHXEM=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/MydkuIGCO3o/hqdefault.jpg",
    "date": "2026-08-19",
    "views": 40,
    "viewsFormatted": "40"
  },
  {
    "url": "https://www.youtube.com/watch?v=zrJYZlWuuHE",
    "title": "Openterface KeyMod — Your Phone as Keyboard, Mouse, Terminal & Gamepad",
    "author": "Crowd Supply",
    "channelAvatar": "https://yt3.ggpht.com/bAUL0NBNgStzCx6LTGQRSoHFg4MMLYWp3w8W7RJejnh5-vIlTZwBBGOCmPFyS7JVtl8qY4C0=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/zrJYZlWuuHE/hqdefault.jpg",
    "date": "2026-08-19",
    "views": 4,
    "viewsFormatted": "4"
  },
  {
    "url": "https://www.youtube.com/watch?v=nl24-rPjOr8",
    "title": "Beta Testing The Openterface Keymod #keymod #openterface",
    "author": "Valleytech Custom Solutions",
    "channelAvatar": "https://yt3.ggpht.com/ZBz7pGNOU1PD-u6cEKWT6q0GKeep5Gh1pTHprSKHQhmHTZQGba71IoCUkQGrzwZSNW2rt8DMQg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/nl24-rPjOr8/hqdefault.jpg",
    "date": "2026-06-05",
    "views": 19232,
    "viewsFormatted": "19.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=uq0F1VKmQdU",
    "title": "USB KVM that You Can Put on a Keychain | Openterface KVM-GO",
    "author": "Home Network Guy",
    "channelAvatar": "https://yt3.ggpht.com/wmQPGuau8ThNtsGR0Kc6m78_55P0_hH6fB4p2dPwHlIXyZ61SGk7yl9ogIMxaWhb8Q0f8zAn=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/uq0F1VKmQdU/hqdefault.jpg",
    "date": "2026-06-06",
    "views": 1875,
    "viewsFormatted": "1.9K"
  },
  {
    "url": "https://www.youtube.com/watch?v=x35Qs89WP_g",
    "title": "Openterface Keymod - Control Any Device with Your Phone",
    "author": "Valleytech Custom Solutions",
    "channelAvatar": "https://yt3.ggpht.com/ZBz7pGNOU1PD-u6cEKWT6q0GKeep5Gh1pTHprSKHQhmHTZQGba71IoCUkQGrzwZSNW2rt8DMQg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/x35Qs89WP_g/hqdefault.jpg",
    "date": "2026-07-13",
    "views": 3222,
    "viewsFormatted": "3.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=OpERf1UFToQ",
    "title": "I can set up a computer without touching it",
    "author": "Level 2 Jeff",
    "channelAvatar": "https://yt3.ggpht.com/6Pcr9KpMMJay2uNTldCH_RH62dJLKvdvZH5_5hTCzImkO8lQg5ctYymsZ9ODb__yA3Nwg36rAg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/OpERf1UFToQ/hqdefault.jpg",
    "date": "2026-08-03",
    "views": 26196,
    "viewsFormatted": "26.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=JK4XaMo8yEI",
    "title": "A USB KVM with VGA! Openterface KVM-GO Review",
    "author": "apalrd's adventures",
    "channelAvatar": "https://yt3.ggpht.com/qencJ8YC4SCPbV_ylp47d-yNIAMTzt6QlncVrJ8FfwRDYeB4m7St7MZNSCDOVx3Qw_9CJxHR5A=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/JK4XaMo8yEI/hqdefault.jpg",
    "date": "2026-02-26",
    "views": 7828,
    "viewsFormatted": "7.8K"
  },
  {
    "url": "https://www.youtube.com/watch?v=BHRGIE8OGYY",
    "title": "Networkless KVM? Yes please open interface kvm-go",
    "author": "KL Tech Videos",
    "channelAvatar": "https://yt3.ggpht.com/mHmleJwkNJwBHMDRv-JXOxpitAiPG5YIsQ4uDApdTKjWu5mD_sUTfnH8VsL9Zwfcg5PKivTQ7Q=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/BHRGIE8OGYY/hqdefault.jpg",
    "date": "2025-12-31",
    "views": 717,
    "viewsFormatted": "717"
  },
  {
    "url": "https://www.youtube.com/watch?v=d9-i7SYAZr8",
    "title": "The KVM-GO is my new EDC KVM!",
    "author": "Symbiiote",
    "channelAvatar": "https://yt3.ggpht.com/OYi4mIbKHArwGmdur42okpmZ3VMRJlMixLH2YOvgv2EqWzzvxx1wgwh0RugCBjTuYAVGne4B=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/d9-i7SYAZr8/hqdefault.jpg",
    "date": "2025-12-29",
    "views": 1505,
    "viewsFormatted": "1.5K"
  },
  {
    "url": "https://www.youtube.com/watch?v=Z7yiAT52_Ew",
    "title": "Openterface uConsole KVM Ext Module V2",
    "author": "RGhandhelds",
    "channelAvatar": "https://yt3.ggpht.com/_fe-uRZnAvnaYwrIWZbCP7t3cLC39MNVMqD2-OzXpwnejdTVTz5F2zYT4EekyvKeeD-2bjLhbg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/Z7yiAT52_Ew/hqdefault.jpg",
    "date": "2026-08-15",
    "views": 248,
    "viewsFormatted": "248"
  },
  {
    "url": "https://www.youtube.com/watch?v=MydkuIGCO3o",
    "title": "Openterface KeyMod: Full Keyboard and Mouse in Your Pocket",
    "author": "Sam's eXperiments logs",
    "channelAvatar": "https://yt3.ggpht.com/QypC0fMJdJDxdf_04lp6TWkuorFPB9pVZD8oOLwclsvRfJsfzCz01iaSl56A1J9lcCHUHXEM=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/MydkuIGCO3o/hqdefault.jpg",
    "date": "2026-08-19",
    "views": 40,
    "viewsFormatted": "40"
  },
  {
    "url": "https://www.youtube.com/watch?v=zrJYZlWuuHE",
    "title": "Openterface KeyMod — Your Phone as Keyboard, Mouse, Terminal & Gamepad",
    "author": "Crowd Supply",
    "channelAvatar": "https://yt3.ggpht.com/bAUL0NBNgStzCx6LTGQRSoHFg4MMLYWp3w8W7RJejnh5-vIlTZwBBGOCmPFyS7JVtl8qY4C0=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/zrJYZlWuuHE/hqdefault.jpg",
    "date": "2026-08-19",
    "views": 4,
    "viewsFormatted": "4"
  },
  {
    "url": "https://www.youtube.com/watch?v=nl24-rPjOr8",
    "title": "Beta Testing The Openterface Keymod #keymod #openterface",
    "author": "Valleytech Custom Solutions",
    "channelAvatar": "https://yt3.ggpht.com/ZBz7pGNOU1PD-u6cEKWT6q0GKeep5Gh1pTHprSKHQhmHTZQGba71IoCUkQGrzwZSNW2rt8DMQg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/nl24-rPjOr8/hqdefault.jpg",
    "date": "2026-06-05",
    "views": 19232,
    "viewsFormatted": "19.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=uq0F1VKmQdU",
    "title": "USB KVM that You Can Put on a Keychain | Openterface KVM-GO",
    "author": "Home Network Guy",
    "channelAvatar": "https://yt3.ggpht.com/wmQPGuau8ThNtsGR0Kc6m78_55P0_hH6fB4p2dPwHlIXyZ61SGk7yl9ogIMxaWhb8Q0f8zAn=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/uq0F1VKmQdU/hqdefault.jpg",
    "date": "2026-06-06",
    "views": 1875,
    "viewsFormatted": "1.9K"
  },
  {
    "url": "https://www.youtube.com/watch?v=x35Qs89WP_g",
    "title": "Openterface Keymod - Control Any Device with Your Phone",
    "author": "Valleytech Custom Solutions",
    "channelAvatar": "https://yt3.ggpht.com/ZBz7pGNOU1PD-u6cEKWT6q0GKeep5Gh1pTHprSKHQhmHTZQGba71IoCUkQGrzwZSNW2rt8DMQg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/x35Qs89WP_g/hqdefault.jpg",
    "date": "2026-07-13",
    "views": 3222,
    "viewsFormatted": "3.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=OpERf1UFToQ",
    "title": "I can set up a computer without touching it",
    "author": "Level 2 Jeff",
    "channelAvatar": "https://yt3.ggpht.com/6Pcr9KpMMJay2uNTldCH_RH62dJLKvdvZH5_5hTCzImkO8lQg5ctYymsZ9ODb__yA3Nwg36rAg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/OpERf1UFToQ/hqdefault.jpg",
    "date": "2026-08-03",
    "views": 26196,
    "viewsFormatted": "26.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=JK4XaMo8yEI",
    "title": "A USB KVM with VGA! Openterface KVM-GO Review",
    "author": "apalrd's adventures",
    "channelAvatar": "https://yt3.ggpht.com/qencJ8YC4SCPbV_ylp47d-yNIAMTzt6QlncVrJ8FfwRDYeB4m7St7MZNSCDOVx3Qw_9CJxHR5A=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/JK4XaMo8yEI/hqdefault.jpg",
    "date": "2026-02-26",
    "views": 7828,
    "viewsFormatted": "7.8K"
  },
  {
    "url": "https://www.youtube.com/watch?v=BHRGIE8OGYY",
    "title": "Networkless KVM? Yes please open interface kvm-go",
    "author": "KL Tech Videos",
    "channelAvatar": "https://yt3.ggpht.com/mHmleJwkNJwBHMDRv-JXOxpitAiPG5YIsQ4uDApdTKjWu5mD_sUTfnH8VsL9Zwfcg5PKivTQ7Q=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/BHRGIE8OGYY/hqdefault.jpg",
    "date": "2025-12-31",
    "views": 717,
    "viewsFormatted": "717"
  },
  {
    "url": "https://www.youtube.com/watch?v=d9-i7SYAZr8",
    "title": "The KVM-GO is my new EDC KVM!",
    "author": "Symbiiote",
    "channelAvatar": "https://yt3.ggpht.com/OYi4mIbKHArwGmdur42okpmZ3VMRJlMixLH2YOvgv2EqWzzvxx1wgwh0RugCBjTuYAVGne4B=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/d9-i7SYAZr8/hqdefault.jpg",
    "date": "2025-12-29",
    "views": 1505,
    "viewsFormatted": "1.5K"
  }
] as HomeVideo[];
